Updated README.md
pranshi112/FoodMenu pull request #21
Opened 2021-10-22 17:10 UTC by Karthick47v2

### Details
Added Documentation about builds

### Checks
- [x] Closes #18

2021-10-22 19:13 UTC, pranshi112 requested changes
@Karthick47v2 There are several changes to make here:

1. Add the `Run the Builds` section at the end of `README.md`
2. For WebGL Build, also include an alternative that allows users to run the build on a web browser by starting a local server. Include the 2 methods like this:
**ALTERNATIVE 1:**
**ALTERNATIVE 2:**

2021-10-23 16:22 UTC, Karthick47v2 commented
@pranshi112 I have updated it, check it.

2021-10-23 16:34 UTC, pranshi112 requested changes
@Karthick47v2 Please include a method to start a local testing server using Python. Refer to the link  [here](https://developer.mozilla.org/en-US/docs/Learn/Common_questions/set_up_a_local_testing_server).

Also, label the first method (that uses Servez) as **ALTERNATIVE 1**, and so on for other methods.

2021-10-23 17:32 UTC, Karthick47v2 commented
@pranshi112 Updated.

2021-10-25 17:04 UTC, pranshi112 requested changes

2021-10-25 17:04 UTC, pranshi112 commented on README.md
> +   If your didn't put any `portNum` by default, this will run on port 8000.
I think it should be _you_ instead of _your_. Rest, everything looks good.

2021-10-25 18:23 UTC, Karthick47v2 commented on README.md
> +   If your didn't put any `portNum` by default, this will run on port 8000.
Now its ok. Thanks for pointing this out.

2021-10-25 19:51 UTC, pranshi112 approved these changes

2021-10-25 19:53 UTC, merged